## Intro to PyTorch

In [37]:
import torch
import numpy as np

PyTorch is similar to numpy but generalises arrays with tensors. Tensors can be differentiable and are an optimised data structure for deep learning.

### Tensors

In [4]:
# empty tensor
x = torch.empty(5,3)
print(x)

tensor([[-1.0645e+11,  4.5916e-41,  0.0000e+00],
        [ 1.7166e-05,  0.0000e+00,  4.7261e-01],
        [-0.0000e+00,  9.2168e-01,  0.0000e+00],
        [ 4.7261e-01,  0.0000e+00,  4.3359e-01],
        [ 0.0000e+00,  4.2676e-01,  0.0000e+00]])


In [6]:
# random tensor
x = torch.rand(5,3)
print(x)

tensor([[0.0282, 0.3585, 0.6230],
        [0.7272, 0.9336, 0.5577],
        [0.0256, 0.5184, 0.4793],
        [0.5550, 0.0032, 0.3403],
        [0.8122, 0.4002, 0.5062]])


In [8]:
# matrix of zeros with dtype long (64bit int)
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
# create a tensor from another tensor
x = x.new_ones(5,3, dtype=torch.double)
print(x)

y = torch.randn_like(x, dtype=torch.float)  # note that we have overridden the type
print(y)                                    # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2144, -1.2757, -0.3748],
        [ 1.4861, -1.1691, -1.7857],
        [-1.8304,  0.2868,  0.9468],
        [-0.2314, -1.2602,  0.8591],
        [ 1.3816,  0.1403, -0.3807]])


In [13]:
# get a tensor's size
print(x.size())

torch.Size([5, 3])


### Tensor Operations

In [22]:
x = torch.ones(5,3)
y = torch.rand(5,3)
print(x + y)

tensor([[1.2433, 1.5297, 1.9173],
        [1.1958, 1.7821, 1.1028],
        [1.5452, 1.6051, 1.9236],
        [1.0654, 1.3024, 1.6642],
        [1.1647, 1.6915, 1.8634]])


In [23]:
# or
result=torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[1.2433, 1.5297, 1.9173],
        [1.1958, 1.7821, 1.1028],
        [1.5452, 1.6051, 1.9236],
        [1.0654, 1.3024, 1.6642],
        [1.1647, 1.6915, 1.8634]])


In [24]:
# in-place addition
y.add_(x)  # note: in-place operations are post-fixed with a `_` eg x.t_()
print(y)

tensor([[1.2433, 1.5297, 1.9173],
        [1.1958, 1.7821, 1.1028],
        [1.5452, 1.6051, 1.9236],
        [1.0654, 1.3024, 1.6642],
        [1.1647, 1.6915, 1.8634]])


In [26]:
# PyTorch supports standard NumPy indexing
print(y[:,1])

tensor([1.5297, 1.7821, 1.6051, 1.3024, 1.6915])


In [30]:
# resize using `torch.view`
x = torch.randn(4,4)
print("X " + "="*83)
print(x)
print(x.size())
y = x.view(16)
print("Y " + "="*83)
print(y)
print(y.size())
z = x.view(-1, 8)  # the size -1 means infer from other dimensions
print("Z " + "="*83)
print(z)
print(z.size())

X ===================================================================================
tensor([[-0.4974,  0.5096,  1.0897,  0.7786],
        [ 0.9801, -0.4962, -1.6765,  1.1932],
        [-0.6939,  0.6411, -1.8604,  0.3828],
        [-0.5180, -0.5231, -0.3075, -0.5778]])
torch.Size([4, 4])
Y ===================================================================================
tensor([-0.4974,  0.5096,  1.0897,  0.7786,  0.9801, -0.4962, -1.6765,  1.1932,
        -0.6939,  0.6411, -1.8604,  0.3828, -0.5180, -0.5231, -0.3075, -0.5778])
torch.Size([16])
Z ===================================================================================
tensor([[-0.4974,  0.5096,  1.0897,  0.7786,  0.9801, -0.4962, -1.6765,  1.1932],
        [-0.6939,  0.6411, -1.8604,  0.3828, -0.5180, -0.5231, -0.3075, -0.5778]])
torch.Size([2, 8])


In [31]:
# use `.item()` to get the value of a one element tensor
a = torch.randn(1)
print(a)
print(a.item())

tensor([-0.6208])
-0.6207857131958008


### From NumPy to PyTorch

PyTorch supports converting tensors to NumPy arrays and vice-versa. Note that the respective tensor and array will share their underlying memory locations and so changing one will change the other.

In [32]:
t = torch.ones(5)
print(t)

tensor([1., 1., 1., 1., 1.])


In [34]:
a = t.numpy()
print(a)

[1. 1. 1. 1. 1.]


In [35]:
t.add_(1)   # note the broadcasting
print(t)

tensor([2., 2., 2., 2., 2.])


In [36]:
print(a)    # see how the array changed

[2. 2. 2. 2. 2.]


In [43]:
# converting a numpy array to a tensor
a= np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [44]:
t = torch.from_numpy(a)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [45]:
np.add(a, 1, out=a)
print(a)

[2. 2. 2. 2. 2.]


In [47]:
print(t)    # now see how the tensor changes

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
